Consolidated backpack into two files

diff --git a/backpack/backpack b/backpack/backpack
--- a/backpack/backpack
+++ b/backpack/backpack
@@ -1,211 +1,178 @@
 # DIY simple package installer, backpack
 # ======================================
 
-# include guard
-[ -n "$BACKPACK_INCLUDED" ] && return || readonly BACKPACK_INCLUDED=1
+BP_COMMAND=$1
+BP_CATEGORY=$2
+shift 2
 
-ghetto_cut() {
-	for i in $1; do echo $i; break; done
+LOCAL_PREFIX="$HOME/.bp"
+LOCAL_BIN=$LOCAL_PREFIX/bin
+LOCAL_PKG=$LOCAL_PREFIX/pkg
+LOCAL_LIB=$LOCAL_PREFIX/lib
+LOCAL_SRC=$LOCAL_PREFIX/src
+LOCAL_LOG=$LOCAL_PREFIX/log
+LOCAL_INC=$LOCAL_PREFIX/include
+mkdir -p $LOCAL_BIN
+mkdir -p $LOCAL_SRC
+mkdir -p $LOCAL_LOG
+mkdir -p $LOCAL_INC
+mkdir -p $LOCAL_PKG
+SELECTED_PKGS=$@
+export PKG_CONFIG_PATH=$LOCAL_PREFIX/share/pkgconfig:$LOCAL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
+#GNULIB_SRCDIR=$LOCAL_INC/gnulib
+export LDFLAGS=-L$LOCAL_LIB $LDFLAGS
+export CPPFLAGS=-I$LOCAL_INC $CPP_FLAGS
+export CFLAGS=-I$LOCAL_INC $CFLAGS
+export CXXFLAGS=-I$LOCAL_INC $CXXFLAGS
+
+SKIP_CATEGORY=0
+SKIP_PACKAGE=0
+
+begin_skip() {
+	SKIP_CATEGORY=1
 }
 
-bp_init() {
-	export LOCAL_PREFIX="$HOME/.bp"
-	export LOCAL_BIN=$LOCAL_PREFIX/bin
-	export LOCAL_PKG=$LOCAL_PREFIX/pkg
-	export LOCAL_LIB=$LOCAL_PREFIX/lib
-	export LOCAL_SRC=$LOCAL_PREFIX/src
-	export LOCAL_LOG=$LOCAL_PREFIX/log
-	export LOCAL_INC=$LOCAL_PREFIX/include
-	mkdir -p $LOCAL_BIN
-	mkdir -p $LOCAL_SRC
-	mkdir -p $LOCAL_LOG
-	mkdir -p $LOCAL_INC
-	mkdir -p $LOCAL_PKG
-	export SELECTED_PKGS=$@
-	export BP_CMD=none
-	export PKG_CONFIG_PATH=$LOCAL_PREFIX/share/pkgconfig:$LOCAL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
-	if [ ! -d "$LOCAL_INC/gnulib" ]; then
-		git clone https://git.savannah.gnu.org/git/gnulib.git $LOCAL_INC/gnulib
-	fi
-	export GNULIB_SRCDIR=$LOCAL_INC/gnulib
+end_skip() {
+	SKIP_CATEGORY=0
 }
 
-bp_command() {
-	case $1 in
-		"install"|"uninstall"|"rm")
-			export BP_CMD=$1
-			;;
-		*)
-			echo "Unrecognized command: $1"
-			exit 1
-			;;
-	esac
+not_selected() {
+	[ "$SKIP_CATEGORY" -ne 0 ] || [ "$SKIP_PACKAGE" -ne 0 ]
 }
 
-bp_process() {
-	if [ "$BP_CMD" == "none" ]; then
-		echo "No command given"
-		exit 1
-	fi
-	source $1
+category() {
+	[ "$BP_CATEGORY" == "$1" ] && end_skip && return 0
+	begin_skip
 }
 
-bp_package() {
+package() {
+	SKIP_PACKAGE=0
+	not_selected && return 0
 	if [[ " $SELECTED_PKGS " =~ .*\ $1\ .* || -z "$SELECTED_PKGS" ]]; then
-		export PKG_NAME=$1
-		export PKG_URL=$2
-		export SRC_DEST=$LOCAL_SRC/$PKG_NAME
-		export BIN_DEST=$LOCAL_BIN/$PKG_NAME
-		case $BP_CMD in
-			"rm")
-				printf "removing directory '$PKG_NAME'\n"
-				bp_remove_existing
-				;;
-			"install")
-				printf "installing package '$PKG_NAME'"
-				bp_fetch_tar $PKG_URL
-				bp_configure_make_install "${@:3}"
-				;;
-			"uninstall")
-				printf "uninstalling package '$PKG_NAME'"
-				bp_make_uninstall
-				;;
-			*)
-				echo "Unrecognized command: $BP_CMD"
-				exit 1
-				;;
-		esac
+		SKIP_PACKAGE=0
+		PKG_NAME=$1
+		SRC_DEST=$LOCAL_SRC/$PKG_NAME
+		BIN_DEST=$LOCAL_BIN/$PKG_NAME
+	else
+		SKIP_PACKAGE=1
 	fi
 }
-export -f bp_package
 
-bp_remove_existing() {
-	[ -e "$SRC_DEST" ] && rm -rf "$SRC_DEST"
+download() {
+	not_selected && return 0
+	PKG_URL=$1
+	printf "downloading %s from %s\n" $PKG_NAME $PKG_URL
+	getfile $PKG_URL $LOCAL_PKG &> $LOCAL_LOG/$PKG_NAME.download
+	printf "extracting %s\n" ${PKG_URL##*\/}
+	bp_extract $PKG_URL &> $LOCAL_LOG/$PKG_NAME.extract
 }
 
-bp_fetch_git() {
-	{
-		[ ! -e "$SRC_DEST" ] \
-			&& git clone "https://github.com/$1" "$SRC_DEST"
-	}	>  $LOCAL_LOG/$PKG_NAME.fetch.out \
-		2> $LOCAL_LOG/$PKG_NAME.fetch.err
-}
-
-bp_download() {
+# getfile <src-url> <dst-dir>
+getfile() {
+	SRC_URL=$1
+	DST_DIR=$2
 	[ ! -x "$(which curl)" ] && [ ! -x "$(which wget)" ] \
 		&& echo "Please install wget or curl." && exit 1
+	# Extract the filename from url and append it to output path
+	DST_PATH=$DST_DIR/${SRC_URL##*\/}
+	[ -s $DST_PATH ] && return 0
 	if [ -x "$(which curl)" ]; then
-		# Extract the filename from url and append it to output path
-		F=$2/${1##*\/}
-		curl -L $1 --output $F
+		curl -L $SRC_URL --output $DST_PATH
 	else
-		wget --no-check-certificate -P $2 $1
+		wget --no-check-certificate -P $DST_DIR $SRC_URL
 	fi
-	#TODO: check if we accidentally received a text file
+#	[ "$(file $DST_PATH)" == *"compressed data"* ] && return 0
+#	echo "$DST_PATH is not compressed data"
+#	return 1
 }
 
-bp_fetch_tar() {
-	{
-		FNAME=${1##*\/}
-		mkdir -p $SRC_DEST
-		#[ ! -e "$LOCAL_PKG/$FNAME" ] &&
-		bp_download $1 $LOCAL_PKG
-		mkdir -p /tmp/bp
-		cd /tmp/bp
-		TARCMD="tar x "
-		case $FNAME in
-			*.tar)
-				$TARCMD -f $LOCAL_PKG/$FNAME
+bp_extract() {
+	ghetto_cut() {
+		for i in $1; do echo $i; break; done
+	}
+	FNAME=${1##*\/}
+	mkdir -p $SRC_DEST
+	mkdir -p /tmp/bp
+	cd /tmp/bp
+	TARCMD="tar x "
+	case $FNAME in
+		*.tar)
+			$TARCMD -f $LOCAL_PKG/$FNAME
+			;;
+		*.tar.gz)
+			gunzip -c $LOCAL_PKG/$FNAME | $TARCMD
+			;;
+		*.tar.xz)
+			xz -c $LOCAL_PKG/$FNAME | $TARCMD -J
+			;;
+		*.tar.bz2)
+			bunzip2 -c $LOCAL_PKG/$FNAME | $TARCMD
+			;;
+		*)
+			echo "Unknown extension: $FNAME"
+			return 1
+			;;
+	esac
+	# Assume a single directory was extracted, try to get its name
+	NEW_DIR=$(ghetto_cut $(ls -t | grep -v "*.tar*"))
+	[ -d "$PWD/$NEW_DIR" ] && mv $PWD/$NEW_DIR/* $SRC_DEST/
+	cd $SRC_DEST
+	rm -rf /tmp/bp
+}
+
+define() {
+	not_selected && return 0
+	[ "$1" != "$BP_COMMAND" ] && return 0
+	shift
+	[ "$1" == ":" ] && shift
+	DELIM=,
+	echo "$BP_COMMAND $PKG_NAME..."
+	mkdir bp-build && cd bp-build
+	while [ $# -gt 0 ]
+	do
+		printf "\t+$1 "
+		local args
+		local cmd
+		local cmdname
+		args=()
+		case $1 in
+			#TODO: instead of hard coding, check for leading "./" to append dir to
+			config|configure)
+				cmdname=$1
+				cmd=$LOCAL_SRC/$PKG_NAME/$1
+				shift
+				args+=(--prefix=$LOCAL_PREFIX)
 				;;
-			*.tar.gz)
-				gunzip -c $LOCAL_PKG/$FNAME | $TARCMD
-				;;
-			*.tar.xz)
-				xz -c $LOCAL_PKG/$FNAME | $TARCMD -J
-				;;
-			*.tar.bz2)
-				bunzip2 -c $LOCAL_PKG/$FNAME | $TARCMD
+			make)
+				cmdname=$1
+				cmd=$1
+				shift
 				;;
 			*)
-				echo "Unknown extension: $FNAME"
+				echo "Unrecognized build command '$1'"
 				return 1
 				;;
 		esac
-		# Assume a single directory was extracted, try to get its name
-		NEW_DIR=$(ghetto_cut $(ls -t | grep -v "*.tar*"))
-		echo "created $NEW_DIR, currently in $PWD"
-		[ -d "$PWD/$NEW_DIR" ] && mv $PWD/$NEW_DIR/* $SRC_DEST/
-		cd $SRC_DEST
-		rm -rf /tmp/bp
-	}	>  $LOCAL_LOG/$PKG_NAME.fetch.out \
-		2> $LOCAL_LOG/$PKG_NAME.fetch.err
-}
-
-bp_make_uninstall() {
-	export SUCCESS=0
-	{
-		cd "$SRC_DEST" \
-		&& ./configure --prefix=$LOCAL_PREFIX $@\
-		&& make -j uninstall \
-		&& export SUCCESS=1
-	}	>  $LOCAL_LOG/$PKG_NAME.make.out \
-		2> $LOCAL_LOG/$PKG_NAME.make.err
-	if [ "$SUCCESS" -eq 0 ]; then
-		printf " failed. Logs written to $LOCAL_LOG\n"
-	else
-		printf " completed\n"
-	fi
-}
-
-bp_configure() {
-	_ARGS="LDFLAGS=-L$LOCAL_LIB CPPFLAGS=-I$LOCAL_INC CFLAGS=-I$LOCAL_INC CXXFLAGS=-I$LOCAL_INC $@"
-	_C=
-	[ -x "./configure" ] && _C=./configure
-	[ -x "./config" ] && _C=./config
-	_FAILURE=1
-	[ -z $_C ] && return 1
-	$_C --prefix=$LOCAL_PREFIX $_ARGS && _FAILURE=0
-	if [ "$_FAILURE" -eq 1 ]; then
-		$_C --prefix=$LOCAL_PREFIX && _FAILURE=0
-	fi
-	return $_FAILURE
-}
-
-bp_configure_make_install() {
-	export SUCCESS=0
-	{
-		cd "$SRC_DEST"
-		if [ -e "autogen.sh" ]; then
-			./autogen.sh \
-			&& printf "." \
-			&& bp_configure $@ \
-			&& printf "." \
-			&& make -j install \
-			&& export SUCCESS=1
-		elif [ ! -x "./configure" -a ! -x "./config" -a -e "Makefile" ]; then
-			mv Makefile Makefile.def
-			sed \
-				-e "/PREFIX.*=.*/c\PREFIX=$LOCAL_PREFIX" \
-				-e "/INSTALL.*=.*/c\INSTALL=$(which install)" \
-				-e "/PRESERVEDIR.*=.*/c\PRESERVEDIR=/tmp/preserve" \
-				Makefile.def > Makefile
-			make -j install \
-			&& export SUCCESS=1
-		else
-			bp_configure $@ \
-			&& make -j install \
-			&& export SUCCESS=1
-		fi
-	}	>  $LOCAL_LOG/$PKG_NAME.make.out \
-		2> $LOCAL_LOG/$PKG_NAME.make.err
-	if [ "$SUCCESS" -eq 0 ]; then
-		printf " failed. Logs written to $LOCAL_LOG:\n"
-		for ll in $PKG_NAME.{fetch,make}.{out,err}; do
-			[ -s $LOCAL_LOG/$ll ] && tail $LOCAL_LOG/$ll
+		while [ $# -gt 0 -a "$1" != "$DELIM" ]
+		do
+			printf " $1"
+			args+=($1)
+			shift
 		done
-	else
-		printf " completed\n"
-	fi
-	# Remove empty logs
-	rm -f $(find $LOCAL_LOG -size 0)
+		printf "\n"
+		shift
+		$cmd "${args[@]}" &> $LOCAL_LOG/$PKG_NAME.$cmdname
+		ex=$?
+		if [ $ex -ne 0 ]
+		then
+			printf "\tfailed with exit code $ex\n"
+			echo "********************************"
+			tail $LOCAL_LOG/$PKG_NAME.$cmdname
+			echo "********************************"
+			return $ex
+		fi
+	done
+	printf "\tcompleted\n"
 }
+
+source $backpack_scripts/packages
