Add gnome-themes.sh

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
 if ! command -v brew &> /dev/null; then
+    echo "Installing brew..."
     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
 
     # This only adds homebrew to PATH on linux
@@ -12,16 +13,35 @@ if ! command -v brew &> /dev/null; then
         echo 'eval $($HOME/.linuxbrew/bin/brew shellenv)' >> $HOME/.bashrc_local
         eval $($HOME/.linuxbrew/bin/brew shellenv)
     fi
-
-    brew install python3
 fi
 
-if command -v pip3 &> /dev/null; then
-    pip3 config -q --user set global.use-feature 2020-resolver
-    pip3 install -q --user --upgrade pip pipx
+if ! command -v brew &> /dev/null; then
+    echo "cannot find brew, exiting"
+    exit 1
+fi
+
+if ! brew list | grep -q python.*3; then
+    echo "Installing python3..."
+    brew install -q python3
+fi
+
+PY3DIR=$(dirname $(which python3))
+PIPDIR=$(dirname $(which pip3))
+if [ "$PY3DIR" != "$PIPDIR" ]; then
+    echo "python3 ($PY3DIR) != pip3 ($PIPDIR), exiting"
+    exit 1
+fi
+
+pip3 config -q --user set global.use-feature 2020-resolver
+pip3 install -q --user --upgrade pip pipx
+
+if ! pipx list | grep -q package\ ansible; then
     pipx install --include-deps ansible
-    ansible-galaxy collection install community.general
-    ANSIBLE_LOCALHOST_WARNING=False ansible-playbook ansible.yml
-else
-    echo "pip3 couldn't be found, please fix and try again"
 fi
+
+if ! ansible-galaxy collection list | grep -q community.general; then
+    ansible-galaxy collection install community.general
+fi
+
+export ANSIBLE_LOCALHOST_WARNING=False
+ansible-playbook ansible.yml
